language: python
python:
      - "3.4"
      - "3.5"
before_install:
      - pip install pytest pytest-cov
      - pip install coveralls
install:
      - python setup.py install
script:
      - coverage run setup.py test
after_success:
      - coveralls
