language: python
python:
      - "3.4"
      - "3.5"
before_install:
      - pip install pytest pytest-cov
      - pip install coveralls
      - git clone https://github.com/rc0r/afl-fuzz
      - make -C afl-fuzz
      - make -C afl-fuzz/llvm_mode
      - sudo make -C afl-fuzz install
install:
      - python setup.py install
script:
      - coverage run --source=afl_utils setup.py test
after_success:
      - coveralls
